def Articles():
    articles = [
        {
            'id': 1,
            'title': 'Article One',
            'body': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, autem alias minus numquam quam mollitia voluptatibus quis error maxime ea quaerat amet cumque optio iure repudiandae eligendi. Aut repudiandae quis veniam officia perferendis dolorem facilis, esse ipsa aliquid autem, quod porro sed ipsam cum fugiat vel quibusdam nobis incidunt voluptatum libero molestiae sint. Nostrum amet corrupti nam possimus autem officiis, provident et minus illum iure consectetur, sunt voluptatem nobis voluptates, eveniet quos voluptate magnam dignissimos ut vitae similique. Numquam beatae illum expedita? Excepturi accusamus dolorem sunt sed eligendi praesentium et ea aperiam quasi qui tempora reiciendis non quod corporis doloremque magni, provident facere? Est, eum deserunt ratione voluptatibus distinctio, dolor unde, blanditiis sed nulla sapiente quidem corrupti tempore accusantium. Perferendis quos id numquam harum sint totam rem, molestias facilis exercitationem doloremque fugiat saepe quae optio qui ad quam velit facere quod et, debitis aut! Nisi fuga placeat debitis soluta amet optio excepturi ea ducimus eveniet repudiandae deleniti error earum tempore temporibus animi mollitia blanditiis, aspernatur quam inventore perspiciatis ex non corporis. Iusto provident, dolores molestiae expedita ut aut, facilis ipsam suscipit debitis laudantium, dolor quae optio ducimus eveniet. Qui, sed placeat. Quibusdam praesentium ducimus dolore eum? Sint rerum corporis temporibus asperiores tenetur hic quae repudiandae excepturi ipsa enim illo dolores in, consequuntur earum dolorem possimus repellat iusto quidem, vel, officiis at velit perferendis aliquam corrupti! Quisquam quae incidunt consequuntur, ratione rem provident earum a necessitatibus minima et magnam magni beatae molestiae, harum autem, sequi modi rerum nisi eligendi nesciunt velit.',
            'author': 'Elias Rodrigues',
            'create_date': '25-04-2017'
        },
        {
            'id': 2,
            'title': 'Article Two',
            'body': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, autem alias minus numquam quam mollitia voluptatibus quis error maxime ea quaerat amet cumque optio iure repudiandae eligendi. Aut repudiandae quis veniam officia perferendis dolorem facilis, esse ipsa aliquid autem, quod porro sed ipsam cum fugiat vel quibusdam nobis incidunt voluptatum libero molestiae sint. Nostrum amet corrupti nam possimus autem officiis, provident et minus illum iure consectetur, sunt voluptatem nobis voluptates, eveniet quos voluptate magnam dignissimos ut vitae similique. Numquam beatae illum expedita? Excepturi accusamus dolorem sunt sed eligendi praesentium et ea aperiam quasi qui tempora reiciendis non quod corporis doloremque magni, provident facere? Est, eum deserunt ratione voluptatibus distinctio, dolor unde, blanditiis sed nulla sapiente quidem corrupti tempore accusantium. Perferendis quos id numquam harum sint totam rem, molestias facilis exercitationem doloremque fugiat saepe quae optio qui ad quam velit facere quod et, debitis aut! Nisi fuga placeat debitis soluta amet optio excepturi ea ducimus eveniet repudiandae deleniti error earum tempore temporibus animi mollitia blanditiis, aspernatur quam inventore perspiciatis ex non corporis. Iusto provident, dolores molestiae expedita ut aut, facilis ipsam suscipit debitis laudantium, dolor quae optio ducimus eveniet. Qui, sed placeat. Quibusdam praesentium ducimus dolore eum? Sint rerum corporis temporibus asperiores tenetur hic quae repudiandae excepturi ipsa enim illo dolores in, consequuntur earum dolorem possimus repellat iusto quidem, vel, officiis at velit perferendis aliquam corrupti! Quisquam quae incidunt consequuntur, ratione rem provident earum a necessitatibus minima et magnam magni beatae molestiae, harum autem, sequi modi rerum nisi eligendi nesciunt velit.',
            'author': 'Nikola Tesla',
            'create_date': '25-04-2017'
        },
        {
            'id': 3,
            'title': 'Article Three',
            'body': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, autem alias minus numquam quam mollitia voluptatibus quis error maxime ea quaerat amet cumque optio iure repudiandae eligendi. Aut repudiandae quis veniam officia perferendis dolorem facilis, esse ipsa aliquid autem, quod porro sed ipsam cum fugiat vel quibusdam nobis incidunt voluptatum libero molestiae sint. Nostrum amet corrupti nam possimus autem officiis, provident et minus illum iure consectetur, sunt voluptatem nobis voluptates, eveniet quos voluptate magnam dignissimos ut vitae similique. Numquam beatae illum expedita? Excepturi accusamus dolorem sunt sed eligendi praesentium et ea aperiam quasi qui tempora reiciendis non quod corporis doloremque magni, provident facere? Est, eum deserunt ratione voluptatibus distinctio, dolor unde, blanditiis sed nulla sapiente quidem corrupti tempore accusantium. Perferendis quos id numquam harum sint totam rem, molestias facilis exercitationem doloremque fugiat saepe quae optio qui ad quam velit facere quod et, debitis aut! Nisi fuga placeat debitis soluta amet optio excepturi ea ducimus eveniet repudiandae deleniti error earum tempore temporibus animi mollitia blanditiis, aspernatur quam inventore perspiciatis ex non corporis. Iusto provident, dolores molestiae expedita ut aut, facilis ipsam suscipit debitis laudantium, dolor quae optio ducimus eveniet. Qui, sed placeat. Quibusdam praesentium ducimus dolore eum? Sint rerum corporis temporibus asperiores tenetur hic quae repudiandae excepturi ipsa enim illo dolores in, consequuntur earum dolorem possimus repellat iusto quidem, vel, officiis at velit perferendis aliquam corrupti! Quisquam quae incidunt consequuntur, ratione rem provident earum a necessitatibus minima et magnam magni beatae molestiae, harum autem, sequi modi rerum nisi eligendi nesciunt velit.',
            'author': 'Norah Jones',
            'create_date': '25-04-2017'
        },
    ]

    return articles